config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
   # Defines the root path route ("/")
  root 'home#index'

  get 'products/:id/price_history' => 'products#price_history', as: :products_price_history

  resources :sites, only: %i[show index edit update] do
    member do
      post 'fetch_data'
      post 'fetch_brands'
      post 'add_categories'
      post 'add_products'
      post 'add_price_metrics'
      post 'connect_retailer_products_with_retailer_brands'
      post 'match_brands'
      post 'match_products'
      post 'connect_products_with_categories'
    end
  end

  resources :products, only: %i[index show]
  resources :brands, only: [] do
    collection do
      get 'autocomplete'
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ShardRecord
  include PgSearch::Model

  belongs_to :brand, optional: true
  belongs_to :category, optional: true
  has_many :retailer_products
  has_many :product_price_metrics, through: :retailer_products

  delegate :name, to: :brand, prefix: true, allow_nil: true
  delegate :name, to: :category, prefix: true, allow_nil: true

  pg_search_scope :search_text, against: %i[name aliases], ignoring: :accents,
                                using: { tsearch: { prefix: true, tsvector_column: 'searchable' } }

  def prices_per_site
    retailer_products.map(&:last_price)
  end

  def lowest_price_history
    product_price_metrics.order(:price).pluck(:price)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  include SearchBar

  before_action :init_filters, only: %i[index]

  def index
    establish_shard_connection do
      @per = 50
      @page = params[:page] || 1
      retailer_products = RetailerProduct.where(
        'EXISTS (SELECT 1 FROM product_price_metrics where retailer_product_id = retailer_products.id)'
      )
      @products = Product.where(id: retailer_products.select(:product_id)) # Use select instead of pluck
      @products = @products.search_text(params[:q]) if params[:q].present?
      @products = @products.where(category: @category_id) if @category_id.present?
      @products = @products.where(brand: @brand_id) if @brand_id.present?
      @products = @products.where(measurement_unit: @measurement_unit) if @measurement_unit.present?
      @products = @products.where.not(bundle: nil) if @bundled
      @products = @products.where(bundle: nil) if params[:bundled].present? && !@bundled
      @products = @products.order(:name)
      @products = @products.page(@page).per(@per)
    end
  end

  def show
    establish_shard_connection do
      @product = Product.find(params[:id])
      @rows = @product.prices_per_site.sort_by{ |p| p[:price] }
    end
  end

  def price_history_diagram
    establish_shard_connection do
      @product = Product.find(params[:id])
      @price_history = @product.lowest_price_history
    end
  end

  def price_history
    establish_shard_connection do
      @product_name = Product.find(params[:id]).name
      retailer_products = RetailerProduct.where(product_id: params[:id])
      @labels = retailer_products.map { |rp| "#{rp.name.gsub('"', '').gsub("''", '')} - #{rp.site_name}" }
      @dates = ProductPriceMetric.where(retailer_product_id: retailer_products.ids)
                                .order(:date)
                                .pluck(:date)
                                .map { |date| date.strftime('%d/%m/%Y') }
                                .uniq
      @prices = retailer_products.map do |rp|
        @dates.map do |date|
          metric = ProductPriceMetric.find_by(retailer_product_id: rp.id, date: date)
          metric&.price || nil
        end
      end
      @datasets = @prices.map.with_index do |prices, index|
        color = "##{SecureRandom.hex(3)}"
        {
          label: @labels[index],
          data: prices.map { |price| price.to_f if price.present? },
          borderColor: color,
          backgroundColor: color,
          borderWidth: 1
        }
      end
    end
  end

  private

  def init_filters
    @category_id = params[:category_id] if params[:category_id].present?
    @brand_id = params[:brand_id] if params[:brand_id].present?
    @measurement_unit = params[:measurement_unit] if params[:measurement_unit].present?
    @bundled = (params[:bundled] == 'true') if params[:bundled].present?
  end
end

app/views/products/index.html.erb
<!-- app/views/products/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Include jQuery -->
  <!-- Include Select2 CSS -->
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />

  <!-- Include Select2 JS -->
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
</head>
<body>

<form class="form-inline" style="margin-bottom: 20px; margin-top: 20px; margin-left: 20px; margin-right: 20px">
  <div class="input-group">
    <%= form_tag('/products', method: 'get') do %>
      <%= text_field_tag :q, params[:q], class: 'form-control mr-sm-2', placeholder: 'Search for name', style: "margin-right: 10px;" %>

      <%= select_tag :category_id, options_from_collection_for_select(@categories_for_selection, :id, :name),
                                include_blank: 'Select a category', class: 'nav-link dropdown-toggle', style: "margin-right: 10px;" %>

      <%= select_tag :brand_id, options_from_collection_for_select(@brands_for_selection, :id, :name),
                                include_blank: 'Select a brand', class: 'nav-link dropdown-toggle', id: 'brand-select' %>

      <%= select_tag :measurement_unit, options_for_select(@units_for_selection, :id),
          include_blank: 'Select a unit', class: 'nav-link dropdown-toggle', style: "margin-left: 10px;" %>

      <div class="form-check form-check-inline">
          <%= radio_button_tag :bundled, 'true', false %>
          <%= label_tag 'bundled_true', 'With Discount' %>
      </div>
      <div class="form-check form-check-inline">
          <%= radio_button_tag :bundled, 'false', false %>
          <%= label_tag 'bundled_false', 'Without Discount' %>
      </div>

      <%= submit_tag 'Search', class: 'btn btn-success', style:"margin-left: 10px;" %>
    <% end %>
  </div>
</form>

<div class="container">
  <h1>Products</h1>

  <div class="d-flex justify-content-center">
    <%= paginate @products %>
  </div>

  <!-- Example Bootstrap Table -->
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Category</th>
        <th scope="col">Brand</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit</th>
        <th scope="col">Discount</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each_with_index do |product, index| %>
        <tr>
          <td><%= (@page.to_i - 1) * @per.to_i + index + 1 %></td>
          <td><%= link_to product.name, product_path(id: product.id) %></td>
          <td><%= product.category_name %></td>
          <td><%= product.brand_name %></td>
          <td><%= product.quantity %></td>
          <td><%= product.measurement_unit %></td>
          <td><%= product.bundle %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex justify-content-center">
    <%= paginate @products %>
  </div>

</div>

</body>
</html>

app/views/products/price_history.html.erb
<!-- app/views/products/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Product</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
  <h1>Price History for "<%= @product_name %>"</h1>


    <tbody>
        <canvas id="measurementChart" width="400" height="200"></canvas>

        <script>
        document.addEventListener("DOMContentLoaded", function() {
            var ctx = document.getElementById('measurementChart').getContext('2d');
            var measurementChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: <%= raw @dates.map(&:to_s) %>, // Convert timestamps to string and pass as JSON
                datasets: [
                    <% @datasets.each do |dataset| %>
                        {
                            label: '<%= dataset[:label] %>',
                            data: <%= dataset[:data].to_s.gsub('nil', 'null') %>,
                            borderColor: '<%= dataset[:borderColor] %>',
                            backgroundColor: '<%= dataset[:backgroundColor] %>',
                            borderWidth: <%= dataset[:borderWidth] %>
                        },
                    <% end %>
                ]
            },
            options: {
                scales: {
                y: {
                    beginAtZero: true
                }
                }
            }
            });
        });
        </script>
    </tbody>

</div>

</body>
</html>

app/views/products/show.html.erb
<!-- app/views/products/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Product</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
  <h1>Products per Retailer</h1>

  <!-- Example Bootstrap Table -->
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Retailer</th>
        <th scope="col">Price</th>
        <th scope="col">Unit Price</th>
      </tr>
    </thead>
    <tbody>
      <%= link_to 'Price History Diagram', products_price_history_path(@product.id), class: 'btn btn-info' %>
      <% @rows.each_with_index do |metric, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= link_to metric[:name], metric[:url] %></td>
          <td><%= metric[:site] %></td>
          <td><%= metric[:price] %></td>
          <td><%= metric[:measurement_unit_price] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

</body>
</html>