config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
   # Defines the root path route ("/")
  root 'home#index'

  get 'products/:id/price_history' => 'products#price_history', as: :products_price_history

  resources :sites, only: %i[show index edit update] do
    member do
      post 'fetch_data'
      post 'fetch_brands'
      post 'add_categories'
      post 'add_products'
      post 'add_price_metrics'
      post 'connect_retailer_products_with_retailer_brands'
      post 'match_brands'
      post 'match_products'
      post 'connect_products_with_categories'
    end
  end

  resources :products, only: %i[index show]
  resources :brands, only: [] do
    collection do
      get 'autocomplete'
    end
  end
end

app/models/site.rb
# frozen_string_literal: true

class Site < ShardRecord
  has_many :retailer_products
  has_many :retailer_brands

  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
end

app/controllers/sites_controller.rb
# frozen_string_literal: true

class SitesController < ApplicationController
  def index
    @sites = Site.all
  end

  def show
    @site = Site.find(params[:id])
  end

  def new
    @site = Site.new
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    if @site.update(site_params)
      redirect_to @site
    else
      render :edit
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    redirect_to sites_path
  end

  def fetch_data
    site = Site.find(params[:id])
    site.fetch_data_job.safe_constantize.perform_later
    flash[:notice] = 'Job is being performed.'
  end

  def fetch_brands
    site = Site.find(params[:id])
    site.fetch_brands_job.safe_constantize.perform_later
    flash[:notice] = 'Job is being performed.'
  end

  def add_categories
    CreateRetailerCategoriesJob.perform_later({ site_id: params[:id] })
    flash[:notice] = 'Job is being performed.'
  end

  def add_products
    CreateRetailerProductsJob.perform_later({ site_id: params[:id] })
    flash[:notice] = 'Job is being performed.'
  end

  def add_price_metrics
    CreateProductPriceMetricsJob.perform_later({ site_id: params[:id] })
    flash[:notice] = 'Job is being performed.'
  end

  def connect_retailer_products_with_retailer_brands
    ConnectRetailerProductsWithRetailerBrandsJob.perform_later({ site_id: params[:id] })
    flash[:notice] = 'Job is being performed.'
  end

  def match_brands
    MatchBrandsJob.perform_later({ site_id: params[:id] })
    flash[:notice] = 'Job is being performed.'
  end

  def match_products
    MatchProductsJob.perform_later({ site_id: params[:id] })
    flash[:notice] = 'Job is being performed.'
  end

  def connect_products_wiht_categories
    ConnectProductsWithCategoriesJob.perform_later({ site_id: params[:id] })
    flash[:notice] = 'Job is being performed.'
  end

  private

  def site_params
    params.require(:site).permit(:name, :url)
  end
end

app/views/sites/edit.html.erb
<!-- app/views/products/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container", style="margin-top: 20px">
  <h1>Site Settings and Actions</h1>

  <div>
   <%= form_with(model: @site, local: true, html: { class: 'needs-validation', novalidate: true }) do |form| %>
        <% if @site.errors.any? %>
          <div class="alert alert-danger">
            <h4 class="alert-heading"><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h4>
            <ul>
              <% @site.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control', required: true %>
          <div class="invalid-feedback">
            Please provide a valid name.
          </div>
        </div>

        <div class="mb-3">
          <%= form.label :url, class: 'form-label' %>
          <%= form.text_field :url, class: 'form-control', required: true %>
          <div class="invalid-feedback">
            Please provide a valid URL.
          </div>
        </div>

        <div class="d-flex justify-content-between">
          <%= form.submit 'Save changes', class: 'btn btn-primary' %>
          <%= link_to 'Back', sites_path, class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  // Example starter JavaScript for disabling form submissions if there are invalid fields
  (function () {
    'use strict'
    var forms = document.querySelectorAll('.needs-validation')

    Array.prototype.slice.call(forms)
      .forEach(function (form) {
        form.addEventListener('submit', function (event) {
          if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
          }

          form.classList.add('was-validated')
        }, false)
      })
  })()
</script>

</div>

</body>
</html>

app/views/sites/index.html.erb
<!-- app/views/products/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
  <h1>Sites</h1>

  <!-- Example Bootstrap Table -->
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">URL</th>
      </tr>
    </thead>
    <tbody>
      <% @sites.each_with_index do |site, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= link_to site.name, site_path(site) %></td>
          <td><%= site.url %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

</body>
</html>

app/views/sites/show.html.erb
<!-- app/views/products/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container", style="margin-top: 20px">
  <h1>Site Settings and Actions</h1>

  <div>
    <li>
      <strong>Site:</strong>
      <%= @site.name %>
    </li>
    <li>
      <strong>URL:</strong>
      <%= @site.url %>
    </li>

    <p><%= link_to 'Edit', edit_site_path(@site), class: 'btn btn-primary' %></p>
  </div>

    <h3>Setup Data</h3>
    <p>
      <%= button_to '1. Fetch Products Data', fetch_data_site_path(@site), method: :post, class: 'btn btn-danger' %>
    </p>
    <p>
      <%= button_to '2. Fetch Brands Data', fetch_brands_site_path(@site), method: :post, class: 'btn btn-danger' %>
    </p>
    <p>
      <%= button_to '3. Add Retailer Categories', add_categories_site_path(@site), method: :post, class: 'btn btn-danger' %>
    </p>
    <p>
      <%= button_to '4. Add Retailer Products', add_products_site_path(@site), method: :post, class: 'btn btn-danger' %>
    </p>
    <p>
      <%= button_to '5. Add Price Metrics', add_price_metrics_site_path(@site), method: :post, class: 'btn btn-danger' %>
    </p>
    <p>
      <%= button_to '6. Connect Retailer Products with Retailer Brands', connect_retailer_products_with_retailer_brands_site_path(@site), method: :post, class: 'btn btn-danger' %>
    </p>
    <p>
      <%= button_to '7. Match Brands', match_brands_site_path(@site), method: :post, class: 'btn btn-danger' %>
    </p>
    <p>
      <%= button_to '8. Match Products', match_products_site_path(@site), method: :post, class: 'btn btn-danger' %>
    </p>
    <p>
      <%= button_to '9. Add Categories to Products', connect_products_with_categories_site_path(@site), method: :post, class: 'btn btn-danger' %>
    </p>

</div>

</body>
</html>