config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
   # Defines the root path route ("/")
  root 'home#index'

  get 'products/:id/price_history' => 'products#price_history', as: :products_price_history

  resources :sites, only: %i[show index edit update] do
    member do
      post 'fetch_data'
      post 'fetch_brands'
      post 'add_categories'
      post 'add_products'
      post 'add_price_metrics'
      post 'connect_retailer_products_with_retailer_brands'
      post 'match_brands'
      post 'match_products'
      post 'connect_products_with_categories'
    end
  end

  resources :products, only: %i[index show]
  resources :brands, only: [] do
    collection do
      get 'autocomplete'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Rails App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand", style="margin-left: 20px">MyApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%# <li class="nav-item active"> %>
          <%= link_to 'Home', root_path, :class => "nav-link" %>
          <%= link_to 'Sites', sites_path, :class => "nav-link" %>
          <%# <%= link_to 'Administration Actions', root_path, :class => "nav-link" %> %>
        <%# </li> %>
      </ul>
    </div>
  </nav>

</header>

<%= yield %>

<footer>
  <%# <p>My Rails App</p> %>
</footer>

</body>
</html>